// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block.proto

package block

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import tx "github.com/iost-official/go-iost/core/tx"
import crypto "github.com/iost-official/go-iost/crypto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BlockType int32

const (
	BlockType_NORMAL   BlockType = 0
	BlockType_ONLYHASH BlockType = 1
)

var BlockType_name = map[int32]string{
	0: "NORMAL",
	1: "ONLYHASH",
}
var BlockType_value = map[string]int32{
	"NORMAL":   0,
	"ONLYHASH": 1,
}

func (x BlockType) String() string {
	return proto.EnumName(BlockType_name, int32(x))
}
func (BlockType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_block_a69d834b056a2d49, []int{0}
}

type BlockHead struct {
	Version              int64    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ParentHash           []byte   `protobuf:"bytes,2,opt,name=parentHash,proto3" json:"parentHash,omitempty"`
	TxsHash              []byte   `protobuf:"bytes,3,opt,name=txsHash,proto3" json:"txsHash,omitempty"`
	MerkleHash           []byte   `protobuf:"bytes,4,opt,name=merkleHash,proto3" json:"merkleHash,omitempty"`
	Info                 []byte   `protobuf:"bytes,5,opt,name=info,proto3" json:"info,omitempty"`
	Number               int64    `protobuf:"varint,6,opt,name=number,proto3" json:"number,omitempty"`
	Witness              string   `protobuf:"bytes,7,opt,name=witness,proto3" json:"witness,omitempty"`
	Time                 int64    `protobuf:"varint,8,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHead) Reset()         { *m = BlockHead{} }
func (m *BlockHead) String() string { return proto.CompactTextString(m) }
func (*BlockHead) ProtoMessage()    {}
func (*BlockHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_block_a69d834b056a2d49, []int{0}
}
func (m *BlockHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHead.Unmarshal(m, b)
}
func (m *BlockHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHead.Marshal(b, m, deterministic)
}
func (dst *BlockHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHead.Merge(dst, src)
}
func (m *BlockHead) XXX_Size() int {
	return xxx_messageInfo_BlockHead.Size(m)
}
func (m *BlockHead) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHead.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHead proto.InternalMessageInfo

func (m *BlockHead) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *BlockHead) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *BlockHead) GetTxsHash() []byte {
	if m != nil {
		return m.TxsHash
	}
	return nil
}

func (m *BlockHead) GetMerkleHash() []byte {
	if m != nil {
		return m.MerkleHash
	}
	return nil
}

func (m *BlockHead) GetInfo() []byte {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *BlockHead) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *BlockHead) GetWitness() string {
	if m != nil {
		return m.Witness
	}
	return ""
}

func (m *BlockHead) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type BlockRaw struct {
	Head                 *BlockHead           `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Sign                 *crypto.SignatureRaw `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"`
	Txs                  []*tx.TxRaw          `protobuf:"bytes,3,rep,name=txs,proto3" json:"txs,omitempty"`
	Receipts             []*tx.TxReceiptRaw   `protobuf:"bytes,4,rep,name=receipts,proto3" json:"receipts,omitempty"`
	TxHashes             [][]byte             `protobuf:"bytes,5,rep,name=txHashes,proto3" json:"txHashes,omitempty"`
	ReceiptHashes        [][]byte             `protobuf:"bytes,6,rep,name=receiptHashes,proto3" json:"receiptHashes,omitempty"`
	BlockType            BlockType            `protobuf:"varint,7,opt,name=blockType,proto3,enum=block.BlockType" json:"blockType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BlockRaw) Reset()         { *m = BlockRaw{} }
func (m *BlockRaw) String() string { return proto.CompactTextString(m) }
func (*BlockRaw) ProtoMessage()    {}
func (*BlockRaw) Descriptor() ([]byte, []int) {
	return fileDescriptor_block_a69d834b056a2d49, []int{1}
}
func (m *BlockRaw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRaw.Unmarshal(m, b)
}
func (m *BlockRaw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRaw.Marshal(b, m, deterministic)
}
func (dst *BlockRaw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRaw.Merge(dst, src)
}
func (m *BlockRaw) XXX_Size() int {
	return xxx_messageInfo_BlockRaw.Size(m)
}
func (m *BlockRaw) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRaw.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRaw proto.InternalMessageInfo

func (m *BlockRaw) GetHead() *BlockHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *BlockRaw) GetSign() *crypto.SignatureRaw {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *BlockRaw) GetTxs() []*tx.TxRaw {
	if m != nil {
		return m.Txs
	}
	return nil
}

func (m *BlockRaw) GetReceipts() []*tx.TxReceiptRaw {
	if m != nil {
		return m.Receipts
	}
	return nil
}

func (m *BlockRaw) GetTxHashes() [][]byte {
	if m != nil {
		return m.TxHashes
	}
	return nil
}

func (m *BlockRaw) GetReceiptHashes() [][]byte {
	if m != nil {
		return m.ReceiptHashes
	}
	return nil
}

func (m *BlockRaw) GetBlockType() BlockType {
	if m != nil {
		return m.BlockType
	}
	return BlockType_NORMAL
}

func init() {
	proto.RegisterType((*BlockHead)(nil), "block.BlockHead")
	proto.RegisterType((*BlockRaw)(nil), "block.BlockRaw")
	proto.RegisterEnum("block.BlockType", BlockType_name, BlockType_value)
}

func init() { proto.RegisterFile("block.proto", fileDescriptor_block_a69d834b056a2d49) }

var fileDescriptor_block_a69d834b056a2d49 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcf, 0x6e, 0xd3, 0x30,
	0x1c, 0x26, 0x4b, 0x9a, 0xa5, 0xbf, 0x16, 0x54, 0x59, 0x08, 0x59, 0x45, 0x42, 0xd1, 0x34, 0xa4,
	0x08, 0x31, 0x47, 0x94, 0x03, 0xe7, 0x71, 0xca, 0x61, 0x6c, 0x92, 0xb7, 0x0b, 0x47, 0x27, 0x73,
	0x5b, 0x6b, 0x4d, 0x1c, 0xd9, 0x2e, 0xcd, 0x9e, 0x84, 0x67, 0xe3, 0x6d, 0x90, 0x7f, 0x49, 0x3a,
	0x7a, 0xe2, 0xe6, 0xef, 0x5f, 0x9c, 0xef, 0x4b, 0x60, 0x56, 0xee, 0x74, 0xf5, 0xc4, 0x5a, 0xa3,
	0x9d, 0x26, 0x13, 0x04, 0xcb, 0x6f, 0x1b, 0xe5, 0xb6, 0xfb, 0x92, 0x55, 0xba, 0xce, 0x95, 0xb6,
	0xee, 0x4a, 0xaf, 0xd7, 0xaa, 0x52, 0x62, 0x97, 0x6f, 0xf4, 0x95, 0x27, 0xf2, 0xca, 0x3c, 0xb7,
	0x4e, 0xe7, 0x56, 0x6d, 0x1a, 0xe1, 0xf6, 0x46, 0xf6, 0xf9, 0xe5, 0x97, 0xff, 0x07, 0xb5, 0x91,
	0xb9, 0xeb, 0x72, 0xd7, 0xf5, 0x91, 0x8b, 0x3f, 0x01, 0x4c, 0xbf, 0xfb, 0x5b, 0x0b, 0x29, 0x1e,
	0x09, 0x85, 0xf3, 0x5f, 0xd2, 0x58, 0xa5, 0x1b, 0x1a, 0xa4, 0x41, 0x16, 0xf2, 0x11, 0x92, 0x0f,
	0x00, 0xad, 0x30, 0xb2, 0x71, 0x85, 0xb0, 0x5b, 0x7a, 0x96, 0x06, 0xd9, 0x9c, 0xff, 0xc3, 0xf8,
	0xa4, 0xeb, 0x2c, 0x8a, 0x21, 0x8a, 0x23, 0xf4, 0xc9, 0x5a, 0x9a, 0xa7, 0x9d, 0x44, 0x31, 0xea,
	0x93, 0x2f, 0x0c, 0x21, 0x10, 0xa9, 0x66, 0xad, 0xe9, 0x04, 0x15, 0x3c, 0x93, 0x77, 0x10, 0x37,
	0xfb, 0xba, 0x94, 0x86, 0xc6, 0xf8, 0x1a, 0x03, 0xf2, 0xb7, 0x1c, 0x94, 0x6b, 0xa4, 0xb5, 0xf4,
	0x3c, 0x0d, 0xb2, 0x29, 0x1f, 0xa1, 0x7f, 0x8a, 0x53, 0xb5, 0xa4, 0x09, 0xfa, 0xf1, 0x7c, 0xf1,
	0xfb, 0x0c, 0x12, 0xec, 0xc6, 0xc5, 0x81, 0x5c, 0x42, 0xb4, 0x95, 0xe2, 0x11, 0x7b, 0xcd, 0x56,
	0x0b, 0xd6, 0xef, 0x7e, 0xac, 0xce, 0x51, 0x25, 0x19, 0x44, 0x7e, 0x54, 0x2c, 0x38, 0x5b, 0xbd,
	0x65, 0xfd, 0xd0, 0xec, 0x7e, 0x1c, 0x9a, 0x8b, 0x03, 0x47, 0x07, 0x79, 0x0f, 0xa1, 0xeb, 0x2c,
	0x0d, 0xd3, 0x30, 0x9b, 0xad, 0xa6, 0xcc, 0x75, 0xec, 0xa1, 0xf3, 0xaa, 0x67, 0xc9, 0x67, 0x48,
	0x8c, 0xac, 0xa4, 0x6a, 0x9d, 0xa5, 0x11, 0x3a, 0x16, 0x83, 0xa3, 0x67, 0xbd, 0xf1, 0xe8, 0x20,
	0x4b, 0x48, 0x5c, 0xe7, 0xb7, 0x90, 0x96, 0x4e, 0xd2, 0x30, 0x9b, 0xf3, 0x23, 0x26, 0x97, 0xf0,
	0x7a, 0xf0, 0x0d, 0x86, 0x18, 0x0d, 0xa7, 0x24, 0x61, 0x30, 0xc5, 0x3e, 0x0f, 0xcf, 0xad, 0xc4,
	0x65, 0xde, 0x9c, 0x36, 0xf4, 0x3c, 0x7f, 0xb1, 0x7c, 0xfa, 0x38, 0x7c, 0x74, 0x0f, 0x08, 0x40,
	0x7c, 0x7b, 0xc7, 0x7f, 0x5c, 0xdf, 0x2c, 0x5e, 0x91, 0x39, 0x24, 0x77, 0xb7, 0x37, 0x3f, 0x8b,
	0xeb, 0xfb, 0x62, 0x11, 0x94, 0x31, 0xfe, 0x23, 0x5f, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x66,
	0x3a, 0x28, 0xed, 0xa5, 0x02, 0x00, 0x00,
}
