FROM ubuntu:18.04

ENV GOVERSION 1.15

# Install Base Tools
RUN apt update && \
        apt install -y git make vim curl wget g++ && \
        rm -rf /var/lib/apt/lists

# Install Go
RUN mkdir /goroot && \
    mkdir /gopath && \
    curl https://storage.googleapis.com/golang/go${GOVERSION}.linux-amd64.tar.gz | \
    tar xzf - -C /goroot --strip-components=1

ENV CGO_ENABLED 1
ENV GOPATH /gopath
ENV GOROOT /goroot
ENV PATH $GOROOT/bin:$GOPATH/bin:$PATH
ENV GO111MODULE on

# Install golangci-lint
RUN curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.35.0

WORKDIR $GOPATH/src/github.com/iost-official/go-iost

CMD ["make"]
