FROM iostio/iost-dev

# Install project
RUN mkdir -p /workdir /workdir/vm/v8vm/v8/libjs /var/lib/iserver /workdir/config
COPY target/iserver target/iwallet target/itest /workdir/
COPY config/docker/iserver.yml config/genesis.yml /var/lib/iserver/
COPY vm/v8vm/v8/libv8/_linux_amd64/* /lib/x86_64-linux-gnu/
COPY vm/v8vm/v8/libjs/* /workdir/vm/v8vm/v8/libjs/
COPY contract/* /workdir/contract/

WORKDIR /workdir

CMD ["./iserver", "-f", "/var/lib/iserver/iserver.yml", "2>&1"]
