// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/common.proto

package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SignatureRaw struct {
	Algorithm            int32    `protobuf:"varint,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Sig                  []byte   `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	PubKey               []byte   `protobuf:"bytes,3,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignatureRaw) Reset()         { *m = SignatureRaw{} }
func (m *SignatureRaw) String() string { return proto.CompactTextString(m) }
func (*SignatureRaw) ProtoMessage()    {}
func (*SignatureRaw) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_9ab2540c58f7b6f3, []int{0}
}
func (m *SignatureRaw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignatureRaw.Unmarshal(m, b)
}
func (m *SignatureRaw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignatureRaw.Marshal(b, m, deterministic)
}
func (dst *SignatureRaw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignatureRaw.Merge(dst, src)
}
func (m *SignatureRaw) XXX_Size() int {
	return xxx_messageInfo_SignatureRaw.Size(m)
}
func (m *SignatureRaw) XXX_DiscardUnknown() {
	xxx_messageInfo_SignatureRaw.DiscardUnknown(m)
}

var xxx_messageInfo_SignatureRaw proto.InternalMessageInfo

func (m *SignatureRaw) GetAlgorithm() int32 {
	if m != nil {
		return m.Algorithm
	}
	return 0
}

func (m *SignatureRaw) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *SignatureRaw) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func init() {
	proto.RegisterType((*SignatureRaw)(nil), "common.SignatureRaw")
}

func init() { proto.RegisterFile("common/common.proto", fileDescriptor_common_9ab2540c58f7b6f3) }

var fileDescriptor_common_9ab2540c58f7b6f3 = []byte{
	// 119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x87, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x9e, 0x52,
	0x18, 0x17, 0x4f, 0x70, 0x66, 0x7a, 0x5e, 0x62, 0x49, 0x69, 0x51, 0x6a, 0x50, 0x62, 0xb9, 0x90,
	0x0c, 0x17, 0x67, 0x62, 0x4e, 0x7a, 0x7e, 0x51, 0x66, 0x49, 0x46, 0xae, 0x04, 0xa3, 0x02, 0xa3,
	0x06, 0x6b, 0x10, 0x42, 0x40, 0x48, 0x80, 0x8b, 0xb9, 0x38, 0x33, 0x5d, 0x82, 0x49, 0x81, 0x51,
	0x83, 0x27, 0x08, 0xc4, 0x14, 0x12, 0xe3, 0x62, 0x2b, 0x28, 0x4d, 0xf2, 0x4e, 0xad, 0x94, 0x60,
	0x06, 0x0b, 0x42, 0x79, 0x49, 0x6c, 0x60, 0x6b, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3f,
	0xab, 0x5e, 0x26, 0x7d, 0x00, 0x00, 0x00,
}
